---
- name: ADD STATIC INTERFACE BINDING TO EPG
  hosts: vlc
  connection: local
  gather_facts: no

  ### MODIFY vars WITH YOUR REQUIRED VALUES  ####
  vars:
    EPGS:

       - { Tenant_name: UNGSC_VLC_DC, AppProfile_name: DC_VLC_INFRA_AP, vlanID: 971, mode: trunk, EPG_name: DC_INFRA_v971_non_routed_EPG, static_binding: "{{ Bindings }}"  }
       - { Tenant_name: UNGSC_VLC_DC, AppProfile_name: DC_VLC_PRO_AP, vlanID: 109, mode: trunk, EPG_name: DC_PRO_v109_10_130_9_0_24_EPG, static_binding: "{{ Bindings }}"  }
       - { Tenant_name: UNGSC_VLC_DC, AppProfile_name: DC_VLC_PRO_AP, vlanID: 111, mode: trunk, EPG_name: DC_PRO_v111_10_130_11_0_24_EPG, static_binding: "{{ Bindings }}"  }
       - { Tenant_name: UNGSC_VLC_DC, AppProfile_name: DC_VLC_PRO_AP, vlanID: 61, mode: trunk, EPG_name: DC_PRO_v61_10_129_17_0_24_EPG, static_binding: "{{ Bindings }}"  }
       - { Tenant_name: UNGSC_VLC_DC, AppProfile_name: DC_VLC_PRO_AP, vlanID: 102, mode: trunk, EPG_name: DC_PRO_v102_10_130_2_0_24_EPG, static_binding: "{{ Bindings }}"  }
       - { Tenant_name: UNGSC_VLC_DC, AppProfile_name: DC_VLC_PRO_AP, vlanID: 103, mode: trunk, EPG_name: DC_PRO_v103_10_130_3_0_24_EPG, static_binding: "{{ Bindings }}"  }
       - { Tenant_name: UNGSC_VLC_DC, AppProfile_name: DC_VLC_PRO_AP, vlanID: 166, mode: trunk, EPG_name: DC_PRO_v166_10_130_16_224_27_EPG, static_binding: "{{ Bindings }}"  }
       - { Tenant_name: UNGSC_VLC_DC, AppProfile_name: DC_VLC_PRO_AP, vlanID: 128, mode: trunk, EPG_name: DC_PRO_v128_10_130_36_0_23_EPG, static_binding: "{{ Bindings }}"  }

      
    Bindings:
        - { Switch_ID: 101, interface_type: switch_port, port: 1/33}
        - { Switch_ID: 102, interface_type: switch_port, port: 1/33}
        - { Switch_ID: 101, interface_type: switch_port, port: 1/34}
        - { Switch_ID: 102, interface_type: switch_port, port: 1/34}
        - { Switch_ID: 101, interface_type: switch_port, port: 1/7}
        - { Switch_ID: 102, interface_type: switch_port, port: 1/7}      
        - { Switch_ID: 101, interface_type: switch_port, port: 1/5}
        - { Switch_ID: 102, interface_type: switch_port, port: 1/5}
        - { Switch_ID: 103, interface_type: switch_port, port: 1/33}
        - { Switch_ID: 104, interface_type: switch_port, port: 1/33}                  



  tasks:

    - name: Add Static Path binding for given EPG
      aci_static_binding_to_epg:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{ item.0.Tenant_name }}"
        ap: "{{ item.0.AppProfile_name }}"
        epg: "{{ item.0.EPG_name }}"
        encap_id: "{{ item.0.vlanID }}"
        interface_mode: "{{ item.0.mode }}"
        interface_type: "{{ item.1.interface_type }}"
        pod: 1
        leafs: "{{ item.1.Switch_ID }}"
        interface: '{{ item.1.port}}'
        state: present
      loop: "{{ EPGS|subelements('static_binding') }}"  
      loop_control:
        pause: "{{ loop_control_pause | default(0) }}"      
      delegate_to: localhost

