devices = [{'bds-dc01-acc-a': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet1/5',
                          'Ethernet1/6']}},
           {'bds-dc01-acc-b': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet1/5',
                          'Ethernet1/6']
           }},
           {'bds-dc01-acc-c': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet1/5',
                          'Ethernet1/6']}},
           {'bds-dc01-acc-d': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet1/5',
                          'Ethernet1/6']
           }},
           {'bds-dc02-acc-a': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet3/1',
                          'Ethernet3/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet3/3',
                          'Ethernet3/4']}},
           {'bds-dc02-acc-b': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet3/1',
                          'Ethernet3/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet3/3',
                          'Ethernet3/4']
           }},
           {'bds-dc02-acc-c': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet3/1',
                          'Ethernet3/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet3/3',
                          'Ethernet3/4']}},
           {'bds-dc02-acc-d': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet3/1',
                          'Ethernet3/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet3/3',
                          'Ethernet3/4']
           }},           
           {'bds-dc02-acc-e': {
           'interfaces': ['Ethernet1/11',
                          'Ethernet1/12',
                          'Ethernet2/11',
                          'Ethernet2/12',
                          'Ethernet1/39',
                          'Ethernet1/40',
                          'Ethernet3/11',
                          'Ethernet3/12']}},
           {'bds-dc02-acc-f': {
           'interfaces': ['Ethernet1/11',
                          'Ethernet1/12',
                          'Ethernet2/11',
                          'Ethernet2/12',
                          'Ethernet1/39',
                          'Ethernet1/40',
                          'Ethernet3/11',
                          'Ethernet3/12']
           }},
           {'bds-dc02-acc-g': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet1/5',
                          'Ethernet1/6']}},
           {'bds-dc02-acc-h': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet1/5',
                          'Ethernet1/6']
           }},
           {'bds-dc02-agg-a': {
           'interfaces': ['Ethernet1/45',
                          'Ethernet1/46',
                          'Ethernet1/47',
                          'Ethernet1/48',
                          'Ethernet3/45',
                          'Ethernet3/46',
                          'Ethernet3/47',
                          'Ethernet3/48',
                          'Ethernet1/25',
                          'Ethernet1/27',
                          'Ethernet3/25',
                          'Ethernet3/27',
                          'Ethernet1/29',
                          'Ethernet1/31',
                          'Ethernet3/29',
                          'Ethernet3/31',
                          'Ethernet1/32',
                          'Ethernet1/42',
                          'Ethernet3/19',
                          'Ethernet3/20',
                          'Ethernet2/25',
                          'Ethernet2/26',
                          'Ethernet4/25',
                          'Ethernet4/26',
                          'Ethernet2/27',
                          'Ethernet2/28',
                          'Ethernet4/27',
                          'Ethernet4/28',
                          'Ethernet2/19',
                          'Ethernet2/20',
                          'Ethernet4/19',
                          'Ethernet4/20']}},
           {'bds-dc02-agg-b': {
           'interfaces': ['Ethernet1/45',
                          'Ethernet1/46',
                          'Ethernet1/47',
                          'Ethernet1/48',
                          'Ethernet3/45',
                          'Ethernet3/46',
                          'Ethernet3/47',
                          'Ethernet3/48',
                          'Ethernet1/25',
                          'Ethernet1/27',
                          'Ethernet3/25',
                          'Ethernet3/27',
                          'Ethernet1/29',
                          'Ethernet1/31',
                          'Ethernet3/29',
                          'Ethernet3/31',
                          'Ethernet1/32',
                          'Ethernet1/42',
                          'Ethernet3/19',
                          'Ethernet3/20',
                          'Ethernet2/25',
                          'Ethernet2/26',
                          'Ethernet4/25',
                          'Ethernet4/26',
                          'Ethernet2/27',
                          'Ethernet2/28',
                          'Ethernet4/27',
                          'Ethernet4/28',
                          'Ethernet2/19',
                          'Ethernet2/20',
                          'Ethernet4/19',
                          'Ethernet4/20']
            }},
           {'vlc-dc01-acc-a': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet3/21',
                          'Ethernet3/22',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet3/23',
                          'Ethernet3/24']}},
           {'vlc-dc01-acc-b': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet3/21',
                          'Ethernet3/22',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet3/23',
                          'Ethernet3/24']
           }},
           {'vlc-dc01-acc-e': {
           'interfaces': ['Ethernet1/11',
                          'Ethernet1/12',
                          'Ethernet3/19',
                          'Ethernet3/20',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet3/23',
                          'Ethernet3/24']}},
           {'vlc-dc01-acc-f': {
           'interfaces': ['Ethernet1/11',
                          'Ethernet1/12',
                          'Ethernet3/19',
                          'Ethernet3/20',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet3/23',
                          'Ethernet3/24']
           }},
           {'vlc-dc02-acc-a': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet2/1',
                          'Ethernet2/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet2/3',
                          'Ethernet2/4']}},
           {'vlc-dc02-acc-b': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet2/1',
                          'Ethernet2/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet2/3',
                          'Ethernet2/4']
           }},
           {'vlc-dc02-acc-c': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet2/1',
                          'Ethernet2/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet2/3',
                          'Ethernet2/4']}},
           {'vlc-dc02-acc-d': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet2/1',
                          'Ethernet2/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet2/3',
                          'Ethernet2/4']
           }},           
           {'vlc-dc02-acc-e': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/1',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet1/5',
                          'Ethernet1/6',
                          'Ethernet1/7',
                          'Ethernet1/8']}},
           {'vlc-dc02-acc-f': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet1/5',
                          'Ethernet1/6',
                          'Ethernet1/7',
                          'Ethernet1/8']
           }},
           {'vlc-dc02-agg-a': {
           'interfaces': ['Ethernet1/44',
                          'Ethernet1/45',
                          'Ethernet1/46',
                          'Ethernet1/47',
                          'Ethernet2/44',
                          'Ethernet2/45',
                          'Ethernet2/46',
                          'Ethernet2/47',
                          'Ethernet2/1',
                          'Ethernet2/3',
                          'Ethernet10/1',
                          'Ethernet10/3',
                          'Ethernet2/5',
                          'Ethernet2/7',
                          'Ethernet10/5',
                          'Ethernet10/7',
                          'Ethernet2/9',
                          'Ethernet2/11',
                          'Ethernet10/9',
                          'Ethernet10/11',
                          'Ethernet2/17',
                          'Ethernet2/19',
                          'Ethernet10/17',
                          'Ethernet10/19',
                          'Ethernet2/13',
                          'Ethernet2/15',
                          'Ethernet10/13',
                          'Ethernet10/15']}},
           {'vlc-dc02-agg-b': {
           'interfaces': ['Ethernet1/44',
                          'Ethernet1/45',
                          'Ethernet1/46',
                          'Ethernet1/47',
                          'Ethernet2/44',
                          'Ethernet2/45',
                          'Ethernet2/46',
                          'Ethernet2/47',
                          'Ethernet2/1',
                          'Ethernet2/3',
                          'Ethernet10/1',
                          'Ethernet10/3',
                          'Ethernet2/5',
                          'Ethernet2/7',
                          'Ethernet10/5',
                          'Ethernet10/7',
                          'Ethernet2/9',
                          'Ethernet2/11',
                          'Ethernet10/9',
                          'Ethernet10/11',
                          'Ethernet2/17',
                          'Ethernet2/19',
                          'Ethernet10/17',
                          'Ethernet10/19',
                          'Ethernet2/13',
                          'Ethernet2/15',
                          'Ethernet10/13',
                          'Ethernet10/15']}},
           {'vlc-edge-agg-a': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet1/31',
                          'Ethernet1/32',
                          'Ethernet1/33',
                          'Ethernet1/34',
                          'Ethernet1/35',
                          'Ethernet1/36',
                          'Ethernet1/37',
                          'Ethernet1/38',
                          'Ethernet1/39',
                          'Ethernet1/40',
                          'Ethernet1/41',
                          'Ethernet1/42',
                          'Ethernet1/43',
                          'Ethernet1/44',
                          'Ethernet1/45',
                          'Ethernet1/46']}},
           {'vlc-edge-agg-b': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet1/31',
                          'Ethernet1/32',
                          'Ethernet1/33',
                          'Ethernet1/34',
                          'Ethernet1/35',
                          'Ethernet1/36',
                          'Ethernet1/37',
                          'Ethernet1/38',
                          'Ethernet1/39',
                          'Ethernet1/40',
                          'Ethernet1/41',
                          'Ethernet1/42',
                          'Ethernet1/43',
                          'Ethernet1/44',
                          'Ethernet1/45',
                          'Ethernet1/46']}},
           {'bds-edge-agg-a': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet1/26',
                          'Ethernet1/27',
                          'Ethernet1/28',
                          'Ethernet1/29',
                          'Ethernet1/33',
                          'Ethernet1/34',
                          'Ethernet1/36',
                          'Ethernet1/37',
                          'Ethernet1/38',
                          'Ethernet1/39',
                          'Ethernet1/42',
                          'Ethernet1/44',
                          'Ethernet1/45',
                          'Ethernet1/46',
                          'Ethernet1/47',
                          'Ethernet1/48',
						  'Ethernet3/1',
						  'Ethernet3/20',
						  'Ethernet3/21',
						  'Ethernet3/22',
						  'Ethernet3/23',
						  'Ethernet3/24']}},
           {'bds-edge-agg-b': {
           'interfaces': ['Ethernet1/1',
                          'Ethernet1/2',
                          'Ethernet1/3',
                          'Ethernet1/4',
                          'Ethernet1/26',
                          'Ethernet1/27',
                          'Ethernet1/28',
                          'Ethernet1/29',
                          'Ethernet1/33',
                          'Ethernet1/34',
                          'Ethernet1/36',
                          'Ethernet1/37',
                          'Ethernet1/38',
                          'Ethernet1/39',
                          'Ethernet1/42',
                          'Ethernet1/44',
                          'Ethernet1/45',
                          'Ethernet1/46',
                          'Ethernet1/47',
                          'Ethernet1/48',
						  'Ethernet3/1',
						  'Ethernet3/20',
						  'Ethernet3/21',
						  'Ethernet3/22',
						  'Ethernet3/23',
						  'Ethernet3/24']}}
    ]                                 

